### ISSUE TITLE
Speedup of ISM algorithm

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [horizon-research/ism-algorithm#1]
How is the speedup of ISM over the baseline calculated in Figure 10 of the paper (ASV)?
Is the DNN run on a CPU or a GPU? If I run the code available in this repo as is using the command given in the README, I can see that the most time-consuming operation is BM. The code in the repo uses GPU for DNN.

What is the correct way to reproduce this result?

**Comment by YuFengUofR** [comment]
the code can only reproduce the accuracy, like the paper mentioned, all operations are done on dedicated hardware
